package com.crstal.ips;

import java.time.ZonedDateTime;
import java.util.concurrent.ThreadLocalRandom;
import java.util.function.Function;
import java.util.stream.IntStream;

public class DistinctIpAutoGenerated {
    public static void main(String[] args) {
        long toEpochMilli = ZonedDateTime.now().toInstant().toEpochMilli();

        int ips = 1_000_000;

        Function<Integer, String> generateIps = i -> {
            int part1 = ThreadLocalRandom.current().nextInt(0, 245);
            int part2 = ThreadLocalRandom.current().nextInt(0, 245);
            int part3 = ThreadLocalRandom.current().nextInt(0, 245);
            int part4 = ThreadLocalRandom.current().nextInt(0, 245);
            return part1 + "." + part2 + "." + part3 + "." + part4;
        };
        long distinctIps = IntStream.range(0, ips)
//                .parallel()
                .mapToObj(generateIps::apply)
                .distinct()
                .count();
        System.out.println("there are " + distinctIps + " distinct ips, total: " + ips);
        System.out.println("Took " + (ZonedDateTime.now().toInstant().toEpochMilli() - toEpochMilli) + "ms");

    }
}
